version: '3.5'

networks:
  fabric-dev:
    external: true

services:
  chaincode.platformer.example.com:
    container_name: chaincode.platformer.example.com
    image: datachainlab/fabric-cosmos-ibc-demo-chaincode:latest
    environment:
      - CHAINCODE_CCID=${CHAINCODE_CCID_PLATFORMER}
      - CHAINCODE_ADDRESS=0.0.0.0:20000
      - FABRIC_IBC_MSPS_DIR=/etc/hyperledger/msps
    volumes:
      - ./msps/PlatformerMSP/msp:/etc/hyperledger/msps/PlatformerMSP
    ports:
      - 20000:20000
    networks:
      - fabric-dev
    restart: on-failure:5
