version: '3.5'

networks:
  fabric-dev:
    name: fabric-dev
    driver: bridge

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:${IMAGE_TAG}
    environment:
      - FABRIC_LOGGING_SPEC=${LOGGING_SPEC}
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=info
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      #- ./config/orderer.yaml:/var/hyperledger/orderer/orderer.yaml
      - ./msps/OrdererMSP/orderers/orderer.example.com/msp:/etc/hyperledger/msp
      - ./artifacts/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050
    networks:
      - fabric-dev
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}

  peer0.platformer.example.com:
    container_name: peer0.platformer.example.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      - FABRIC_LOGGING_SPEC=${LOGGING_SPEC}
      - CORE_PEER_ID=peer0.platlformer.example.com
      - CORE_PEER_ADDRESS=peer0.platformer.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.platformer.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.platformer.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.platformer.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=PlatformerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-dev
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_CHAINCODE_MODE=dev
    volumes:
        - /var/run/:/host/var/run/
        - ./msps/PlatformerMSP/peers/peer0.platformer.example.com/msp:/etc/hyperledger/msp
        - ./config/core.yaml:/etc/hyperledger/fabric/core.yaml
        - ./external:/builders/external
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer.example.com
    networks:
      - fabric-dev
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}

  fabric-cli:
    container_name: fabric-cli
    image: hyperledger/fabric-tools:${IMAGE_TAG}
    tty: true
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.platformer.example.com
      - CORE_PEER_ADDRESS=peer0.platformer.example.com:7051
      - CORE_PEER_LOCALMSPID=PlatformerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-dev
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './scripts/createChannel.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./msps/PlatformerMSP/users/Admin@platformer.example.com/msp:/etc/hyperledger/msp
        - ./external:/etc/hyperledger/fabric/external
        - ./:/opt/gopath/src/chaincodedev/
    depends_on:
      - orderer.example.com
      - peer0.platformer.example.com
    networks:
      - fabric-dev
    extra_hosts:
      - host.internal:${LOCAL_HOST_IP}
