# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.5'

networks:
  fabric-dev:
    name: fabric-dev
    driver: bridge

services:
  ca.platformer.example.com:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    container_name: ca.platformer.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/fabric-ca/PlatformerCA:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-dev

  ca.example.com:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    container_name: ca.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/fabric-ca/OrdererCA:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-dev
